# Generated by Django 2.1.5 on 2019-11-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=17)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='backendapp.Currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Currency')),
            ],
        ),
    ]
